site_name: Cocovii文案汇总

nav: # 网站导航栏配置
  - 主页: index.md
  - 关于: about.md
  - 战神5: # 这是主菜单项，下包含子菜单
    - 《索尔与海姆达尔——《战神5：诸神黄昏》人物与剧情深度解读》: game_analysis/odin_kratos.md
    - 索尔与海姆达尔: game_analysis/thor_heimdall.md
  - 其他内容: other.md

theme: # 主题设置
  name: material # 使用 mkdocs-material 主题，如果未安装，请将此行改为 'readthedocs' 或 'mkdocs'
  palette: # 配色方案 (仅 mkdocs-material 支持)
    primary: blue
    accent: light blue
  features: # 主题特性 (仅 mkdocs-material 支持)
    - content.tabs
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.indexes
    - toc.integrate

markdown_extensions: # Markdown 扩展 (提供更多 Markdown 功能)
  - attr_list # 允许为 Markdown 元素添加属性
  - md_in_html # 允许在 HTML 块中使用 Markdown
  - admonition # 支持提示框 (Note, Warning 等)
  - pymdownx.details # 支持详情/折叠块
  - pymdownx.superfences # 增强代码块
  - pymdownx.tabbed:
      alternate_style: true # 支持标签页
  - pymdownx.critic # 评论标记 (用于审阅文档)
  - pymdownx.keys # 键盘按键
  - pymdownx.mark # 标记文本
  - pymdownx.tilde # 下划线/删除线
  - pymdownx.emoji: # 表情符号支持
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg