site_name: Cocovii文案汇总

nav: # 网站导航栏配置
  - 主页: index.md
  - 《战神5：诸神黄昏》人物与剧情深度解析: # 这是主菜单项，下包含子菜单
    - 奥丁与奎托斯: god-of-war-ragnarok/odin_kratos.md
    - 索尔与海姆达尔: god-of-war-ragnarok/thor_heimdall.md
    - 芙蕾雅与希芙: god-of-war-ragnarok/freya_sif.md
  - 幕间的游戏杂谈: # 这是父级菜单项
    - 自由只会倒在她自己的剑下——从《INSIDE》到《生化奇兵》深度解读解析 随笔漫谈: Interval/inside-bioshock-freedom-analysis.md # 子菜单项1
    - 剧情是好还是坏、赤鬼青鬼都是鬼——《原神》关于剧情、关于一斗随笔: Interval/genshin-impact-story-analysis.md # 子菜单项2
    - 它的魅力究竟在哪儿？——《邪恶冥刻-Inscryption》解读与评价: Interval/inscryption-deep-dive-review.md # 子菜单项3
  - 《极乐迪斯科》深度解读与解析:
    - 野兽般的第一印象、有关艺术风格: Disco-Elysium/art-style-part1.md
    - 像狗一样: Disco-Elysium/dog-like-part2.md
    - 爬满蛆虫的意识: Disco-Elysium/consciousness-part3.md
    - 死亡的“价值”: Disco-Elysium/death-value-part4.md
    - 扼腕的幽灵: Disco-Elysium/the_ghost_of_regret-part5.md
  - 虚拟世界的美与浪漫: 
    - 自恋是浪漫的开端——〈艾尔登法环〉: Aesthetics&Romance-in-virtual-world/elden_ring_art_analysis_part_1.md
    - 绫波丽的微笑——〈艾尔登法环〉与〈荒野大镖客2：救赎〉: Aesthetics&Romance-in-virtual-world/elden_ring_red_dead_redemption_2_beauty_romance_part_2.md
    - 聆听深渊——〈塞尔达传说：旷野之息〉深度解读 : Aesthetics&Romance-in-virtual-world/zelda_breath_of_the_wild_beauty_romance_part_3.md
    - 苏联美学的至上主义与构成主义——〈原子之心〉艺术前瞻: Aesthetics&Romance-in-virtual-world/atomic_heart_soviet_aesthetics_part_4.md
    - 象征性的冲动——〈原子之心〉前瞻 双子机器人: Aesthetics&Romance-in-virtual-world/atomic_heart_twin_robots_beauty_romance_interlude.md
    - 右伶梦蝶——〈原子之心〉艺术与剧情解读释义: Aesthetics&Romance-in-virtual-world/atomic_heart_plot_analysis_part_5.md
    - 薛定谔的猫——〈原子之心〉剧情剧作解读分析: Aesthetics&Romance-in-virtual-world/atomic_heart_plot_analysis_part_6.md
    - 怪核与梦核的美学释义——后室系列: Aesthetics&Romance-in-virtual-world/liminal_spaces_aesthetics_backrooms_part_3_2.md
    - 听话的好孩子——怪核与梦核心理意象释义: Aesthetics&Romance-in-virtual-world/liminal_spaces_aesthetics_backrooms_part_3.md
    - 星空——〈星际拓荒〉的魅力: Aesthetics&Romance-in-virtual-world/outer_wilds_charm_beauty_romance_part_8.md
    - 疯癫与艺术——〈蔑视〉的艺术风格解读释疑: Aesthetics&Romance-in-virtual-world/scorn_art_style_analysis_part_9.md
    - 野蛮与艺术——〈蔑视〉的艺术风格解读: Aesthetics&Romance-in-virtual-world/scorn_art_style_analysis_part_10.md
    - 游戏成瘾者——以〈艾尔登法环〉聊我们为什么会喜欢游戏: Aesthetics&Romance-in-virtual-world/game_addiction_elden_ring_part_6.md
    - 死亡的希望——〈蔑视〉艺术风格解读释义: Aesthetics&Romance-in-virtual-world/scorn_art_style_analysis_part_11.md
    - AI绘画的现实与虚幻: Aesthetics&Romance-in-virtual-world/ai_painting_reality_and_illusion_interlude_7.md
    - 被抹去的东西——〈控制〉艺术风格解读与解析: Aesthetics&Romance-in-virtual-world/control_art_style_analysis_part_12.md
    - 要守规矩——规则类怪谈 心理意象解读释义: Aesthetics&Romance-in-virtual-world/rules_horror_psychological_interpretation_part_13.md
    - 恐怖、神秘与疯狂——〈恶灵附身〉艺术解读与展示方法: Aesthetics&Romance-in-virtual-world/the_evil_within_art_analysis_part_14.md
    - 她是谁——〈恶灵附身〉深度解读解析: Aesthetics&Romance-in-virtual-world/the_evil_within_analysis_part_15.md
    - 废土文化的美学解读 物、事、人: Aesthetics&Romance-in-virtual-world/wasteland_culture_aesthetics_part_16.md
    - 吸血鬼、超自然文化的美学解读: Aesthetics&Romance-in-virtual-world/vampire_supernatural_aesthetics_part_17.md
    - 洛夫克拉夫特的克苏鲁文学 解读释义: Aesthetics&Romance-in-virtual-world/lovecraft_cthulhu_madness_analysis_part_18.md
    - 被隐藏的意义 小岛秀夫——〈合金装备：幻痛〉美学解读前瞻篇: Aesthetics&Romance-in-virtual-world/kojima_productions_metal_gear_solid_phantom_pain_aesthetics_part_19.md
    - 废土文化的美学 荒芜之地的朋克: Aesthetics&Romance-in-virtual-world/wasteland_culture_aesthetics_wasteland_punk_part_20.md
    - 不可名状的恐惧 克苏鲁文学解读释义: Aesthetics&Romance-in-virtual-world/lovecraft_cthulhu_fear_analysis_part_21.md
    - 女巫 坩锅里的天使与恶魔: Aesthetics&Romance-in-virtual-world/witch_angels_demons_cauldron_part_22.md


theme: # 主题设置
  name: material # 使用 mkdocs-material 主题，如果未安装，请将此行改为 'readthedocs' 或 'mkdocs'
  palette: # 配色方案 (仅 mkdocs-material 支持)
    primary: blue
    accent: light blue
  features: # 主题特性 (仅 mkdocs-material 支持)
    - content.tabs
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.indexes
    - toc.integrate

markdown_extensions: # Markdown 扩展 (提供更多 Markdown 功能)
  - attr_list # 允许为 Markdown 元素添加属性
  - md_in_html # 允许在 HTML 块中使用 Markdown
  - admonition # 支持提示框 (Note, Warning 等)
  - pymdownx.details # 支持详情/折叠块
  - pymdownx.superfences # 增强代码块
  - pymdownx.tabbed:
      alternate_style: true # 支持标签页
  - pymdownx.critic # 评论标记 (用于审阅文档)
  - pymdownx.keys # 键盘按键
  - pymdownx.mark # 标记文本
  - pymdownx.tilde # 下划线/删除线
  - pymdownx.emoji: # 表情符号支持
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg