name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出仓库代码

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 使用最新的 Python 3 版本

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material # 安装 MkDocs 和 mkdocs-material 主题

      - name: Build MkDocs site
        run: mkdocs build # 构建你的网站，生成 site 文件夹

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # 使用一个专门的 Action 来部署到 gh-pages 分支
        if: github.ref == 'refs/heads/main' # 只有在 main 分支上才部署
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 提供的自动令牌
          publish_dir: ./site # 指定要部署的文件夹是 ./site
          publish_branch: gh-pages # 指定部署到 gh-pages 分支 (这是 GitHub Pages 的默认分支)